version: '3'

services:
  alice-mediator:
    build: ..
    image: aries-framework-javascript
    command: ./scripts/run-mediator.sh alice
    networks:
      - hyperledger
    ports:
      - 3001:3001

  bob-mediator:
    build: ..
    image: aries-framework-javascript
    command: ./scripts/run-mediator.sh bob
    networks:
      - hyperledger
    ports:
      - 3002:3002

networks:
  hyperledger:
